# Operation-Sassi-Wrapper
Practicing the art of building a portfolio with github 
title: Ingrid Sassi
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: time machine-theme
